import streamlit as st



def show_privacy():


    streamlit_style = """
        <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins');

        html, body, [class*="css"]  {
        font-family: 'Poppins', sans-serif;
        }
        </style>
        """
    st.markdown(streamlit_style, unsafe_allow_html=True)

    st.title("PRIVACY STATEMENT")
    st.write("")
    st.write("PRIVACY CONSENT STATEMENT")
    st.write("Holy Angel University respects the student’s privacy and are committed to protecting information. By using the enrollment prediction app, applicants are consenting to the collection, use, and disclosure of personal information as described in this privacy policy.")
    st.write("")
    st.write("COLLECTION OF PERSONAL INFORMATION")
    st.write("Holy Angel University collects personal information, such as the applicant’s province, financial source, parent’s educational attainment, parent’s working status, and some personality questionnaires for the purpose of providing data to the enrollment prediction app.")
    st.write("")
    st.write("DISCLOSURE OF PERSONAL INFORMATION")
    st.write("Holy Angel University may share the data provided on the application to the authorized personnel of the university for marketing and academic purposes. The university will not sell or disclose any of the applicant’s information to unauthorized personnel.")
    st.write("")
    st.write("DATA RETENTION")
    st.write("The data uploaded by the user will not be stored on the application. However, results may be generated by the user to fulfill the purposes for which it was collected. The length of time that the university will retain the information will vary depending on the type of information and the purposes for which it was collected.")
    st.write("The university will securely destroy or anonymize the information once it is no longer needed for the purposes for which it was collected, or as required by applicable laws and regulations.")
    st.write("")
    st.write("CONSENT")
    st.write("By using the enrollment prediction app, the applicant is consenting the university to the collection, use, and disclosure of personal information as described in this privacy policy. The applicant has the right to withdraw the consent at any time by contacting us the ITEC and ITSS Department.")
